server:
  port: 8080
logging:
  config: classpath:logback-spring.xml
#  file: blog.log
#  level:
#    com.melelee.melelee.controler: debug
#    root: info
#  path: logs/

spring:
  profiles:
    active: dev
#    active: prod
  datasource:
    #详解
    #https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    #https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://45.78.57.75:3306/melelee?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&&useSSL=false
    username: melelee
    password: HVM8bTPY7gSyDQrVBX7eGSfUqUO3KQtMov2s0dkSWywOQyUQPMaQKP5wiimXHMDtweqxUhnUVjjZTU5zunX/6A==
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
#swagger:
#  base-package: com.melelee.melelee