spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Password124
  devtools:
    restart:
      enabled: true
#      additional-paths: src/main/java