server:
  port: 8080
logging:
  config: classpath:logback-spring.xml
#  file: blog.log
#  level:
#    com.melelee.melelee.controler: debug
#    root: info
#  path: logs/

spring:
  profiles:
    active: dev
#    active: prod
  datasource:
      #详解
      #https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
      #https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.17.28.75:4001/cloud?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: midcuser
    password: msHwmgRM2G6kpzGh7C3uXqZ8s9aUtHlTuR4mz+zWYRx2PmV59g6bwXoQ/cwwQgeBjp3MXnfdq26yHM0FQe2DiQ==
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALhfaofF2OCCW09U6mXNj3dF3+i0M+3E/lNmXDxou6d3aUxPK8bi3z/03nhbppT/ZuK7/Ry677J9KScAMXc5RIMCAwEAAQ==
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      validation-query: select 'x'
      validation-query-timeout: 10
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
#      max-evictable-idle-time-millis: 1\
      connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.druid.publickey}
      filter:
        config:
          enabled: true
        stat:
          merge-sql: true
          slow-sql-millis: 5000
      stat-view-servlet:
#        deny:
#        allow:
        login-username: melelee
        login-password: 123123
        reset-enable: false
        url-pattern: /druid/*
        enabled: true
mybatis-plus:
  configuration:
    default-executor-type: simple
    default-statement-timeout: 25000
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: false
  mapper-locations: classpath:mapper/*/*.xml
#swagger:
#  base-package: com.melelee.melelee

job.dataimport.cron: 0 0 1 * * ?

yltest:
  token:
    user: 34000001
    password: 123456
    granttype: client_credentials
    url: https://172.17.28.74/oauth/token
url:
  getbusinessid: https://172.17.28.74/midc-externalservice/task/apply?orgId=
  uploadfile: https://172.17.28.74/midc-externalservice/task/upload/batch
dcm:
  path: /home/midcuser/tmp/dcm
  dir: /home/midcuser/tmp/dir