server:
  port: 8080
#  servlet:
#    context-path: /melelee
spring:
  profiles:
    active: dev
  application:
    name: melelee
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
logging:
  level:
    root: info
  path: ./logs/
  file:
    max-size: 100MB
    max-history: 30
swagger:
  enabled: true
  base-package: com.melelee
