server:
  port: 80
spring:
  profiles:
    active: dev
  application:
    name: melelee
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    root: info
  path: ./logs/
  file:
    max-size: 100MB
    max-history: 30
swagger:
  base-package: com.melelee.melelee.controller
shiro:
  web:
    enabled: false
  #没有权限默认跳转的页面，登录的用户访问了没有被授权的资源自动跳转到的页面。
  unauthorizedUrl: /403
  #登录成功默认跳转页面，不配置则跳转至”/”，可以不配置，直接通过代码进行处理。
  successUrl: /success
  #未登录时，访问需要登录的url时，跳转的url
  loginUrl: /login